### ISSUE TITLE
UseQuartzSimpleInjector interfears with Topshelf install and uninstall

### ISSUE THREAD

**Issue by gbanister** [tynor88/Topshelf.SimpleInjector#1]
If you use  config.UseQuartzSimpleInjector(_container); as is done in the QuartzAsService.Sample,  the TopShelf install and uninstall operations succeed however they do not complete, causing he user to have to end the process by using ctrl+c.  This becomes an issue for spripted/automated deployments.  In order to work around this behavior the following line must be executed durring an install or uninstall.
ScheduleJobServiceConfiguratorExtensions.SchedulerFactory().Shutdown();

I suspect the root of this issue is related to the creation of the scheduler via the call schedulerFactory.GetScheduler()  in the SetupQuartzSimpleInjector() method.  Perhaps this method could determine if a TopShelf install or uninstall operation is being executed and if so then exit the SetupQuartzSimpleInjector without calling schedulerFactory.GetScheduler().

**Comment by tynor88** [comment]
I have fixed this issue, by checking the CommandLine - I could not find another easy way to do it.

See code here: https://github.com/tynor88/Topshelf.SimpleInjector/commit/4e59bf4363f2e86aeb04cebf5a96ef8ffe9c786d

**Comment by vadimshaporov** [comment]
I might have faced something similar. When using Topshelf+Quartz+SimpleInjector and adding listener to the job, everything works fine (services injected to the job as expected), but when I execute install, I get the error saying that IScheduler was not registered in the container. 
I tried registering it this way: 
var schedulerFactory = new StdSchedulerFactory();
Container.Register<IScheduler>(() => schedulerFactory.GetScheduler());
install worked, but as gbanister mentioned, I have to do ctrl+c to complete install and uninstall. When running application by F5, it crashes saying IScheduler is already registered.
Everything works fine if I don't add listener to the job.

**Comment by tynor88** [comment]
@vadimshaporov Can you provide a full code example to prove this bug?

**Comment by vadimshaporov** [comment]
[Program.zip](https://github.com/tynor88/Topshelf.SimpleInjector/files/68155/Program.zip)
I attached the modified program.cs from QuartzAsService.Sample (added listener).

**Comment by tynor88** [comment]
I've added support for JobListeners as per this https://github.com/tynor88/Topshelf.SimpleInjector/commit/ccce22a2624f20d2fc8e48b3558071e97700a792 commit. I will publish an updated NuGet package soon.

**Comment by tynor88** [comment]
This is pushed to NuGet now. Please upgrade to the latest version.
