### ISSUE TITLE
Support for DefaultScopedLifestyle

### ISSUE THREAD

**Issue by Simble** [tynor88/Topshelf.SimpleInjector#16]
I've recently migrated to Simple Injector 3.1.2 and started using the new [LifeStyle.Scoped feature](https://simpleinjector.org/blog/2015/08/simple-injector-v3-is-here/).

However, this causes Quartz.NET to fail (I use a shared DR-layer), because the container.BeginLifetimeScope() is never called and therefore no services can be resolved. 

Is there a way I can configure your package to make this work?

**Comment by tynor88** [comment]
Hi @Simble,

Can you please provide a running Code Example where this is failing? Perhaps on https://dotnetfiddle.net/

**Comment by Simble** [comment]
Unfortunately, I cannot get dotnetfiddle to include your Nuget package, so I included a basic example:

```
private static void Main()
{
    Container container = new Container();

    // Set scope base on the the type of application
    // Would be "WebRequestLifestyle" for web apps, 
    // for services the "Lifetime" scope would be best suited
    container.Options.DefaultScopedLifestyle = new LifetimeScopeLifestyle();

    // 1. External layers (executed in different assembly, pasted here to clarify)
    container.Register<ISalesContext, SalesDbContext>(LifeStyle.Scoped);
    ...

    // 2. App-specific registrations
    container.Register<TaskManagerService>();
    ...

    // Setup Topshelf and Quartz
    HostFactory.Run(config =>
    {
        config.UseQuartzSimpleInjectorWithDecorators(container, Assemblies.ToArray());

        container.Verify();

        config.Service<TaskManagerService>(s =>
        {
            // Let Topshelf use it
            s.ConstructUsingSimpleInjector();
            s.WhenStarted((service, control) => service.Start());
            s.WhenStopped((service, control) => service.Stop());
        });
    });
}
```

This compiles, is correctly verified by Simple Injector, but as soon as Quartz.NET starts requesting services through Simple Injector, it fails because the scope has not been initialised through:

```
container.BeginLifetimeScope();
```

**Comment by tynor88** [comment]
You should decorate your IJob with a LifeTimeScopeDecorater:

```C#
        public class LifetimeScopeDecoratorFuncTFactory : IJob
        {
            private readonly Func<IJob> _decorateeFactory;
            private readonly Container _container;

            public LifetimeScopeDecoratorFuncTFactory(Func<IJob> decorateeFactory, Container container)
            {
                _decorateeFactory = decorateeFactory;
                _container = container;
            }

            public void Execute(IJobExecutionContext context)
            {
                using (_container.BeginLifetimeScope())
                {
                    var job = _decorateeFactory.Invoke();
                    job.Execute(context);
                }
            }
        }
```

And register it like:
```C#
_container.RegisterDecorator(typeof(IJob), typeof(LifetimeScopeDecoratorFuncTFactory));
```

I have actually created a Sample project for this example, please check it here: https://github.com/tynor88/Topshelf.SimpleInjector/blob/dev/Samples/Topshelf.SimpleInjector.Quartz.Decorators.Sample/Program.cs .

Let me know if it works our for you :-)

**Comment by Simble** [comment]
Thank you! That did the trick :-)

**Comment by tynor88** [comment]
Great, glad it worked out for you :+1:
