### ISSUE TITLE
Topshelf & Quartz

### ISSUE THREAD

**Issue by stevenfirstrowinc** [tynor88/Topshelf.SimpleInjector#3]
hi,

I just found this project today and I'm hoping you can give a little guidance to the samples.  

* What's the difference between ScheduleQuartzJobAsService and ScheduleQuartzJob methods?
* if I use ScheduleQuartzJobAsService can I just use the quartz xml scheduler?

Thanks for any help.

**Comment by mgonzales3** [comment]
Quartz is a scheduler api
-  ScheduleQuartzJobAsService 
   * will have a scheduled trigger - this sample uses the CronTrigger and runs at that interval
   * will have the ability to start, stop and pause like a windows service

- ScheduleQuartzJob 
   * While this will have a trigger to it is meant to stop once the program stops.

Here is a high-level view of the api
http://tpstatic.com/img/usermedia/DQJBdpyj5Eaj4uZHzUmpBg/original.png

**Comment by stevenfirstrowinc** [comment]
Is there any way to have the schedule picked up from the xml file as here [examplexmlconfig](https://basquang.wordpress.com/2014/08/06/quartz-net-configure-job-in-xml-using-quartz-plug-in-xmlschedulingdataprocessorplugin/)?  

Thanks for the quick response.

**Comment by mgonzales3** [comment]
To use the examplexmlconfig you have to add the quartz configuration whether in your app.config or use it as a separate file (quartz.config)

https://github.com/quartznet/quartznet/blob/master/server/Quartz.Server/quartz.config

And when you request for jobs
GetScheduler();
It will return all jobs for that instance

**Comment by stevenfirstrowinc** [comment]
ok so it looks like [UseQuartzSimpleInjector](https://github.com/tynor88/Topshelf.SimpleInjector/blob/fd67a1409bebfb47839efb07361ba5177327d31c/Source/Topshelf.SimpleInjector.Quartz/SimpleInjectorScheduleJobServiceConfiguratorExtensions.cs)  already calls this, does that mean I just need to make sure I have the config files setup properly?

**Comment by mgonzales3** [comment]
I'm reviewing that project too but in reviewing ioc containers (SimpleInjector, StructureMap, etc...) this appears to be a another abstracted container that you can add to your into your project so you integrate quartz and topshelf into your project.  The layers to include will be 

* quartz
* topshelf
* SimpleInjector (ioc container)
* QuartzSimpleInjector (instance injector for your project)
* <yournamespace>.dll

**Comment by tynor88** [comment]
@stevenfirstrowinc yes, you just need to make sure to have the config files setup properly. Have a look [here for an example](https://gist.github.com/Dervall/2292142)

**Comment by tynor88** [comment]
@mgonzales3 Yes indeed, i found myself doing alot of scheduled jobs with Quartz.NET and Topshelf, in combination with SimpleInjector (my favourite :)) IoC container. So this project is for the lazy people who don't want to do the same biolerplate code over and over again.

There are similar projects for Quartz.NET / Topshelf in combination with other IoC Containers:
[Autofac & Quartz](https://github.com/alexandrnikitin/Topshelf.Autofac)
[Ninject & Quartz](https://github.com/dtinteractive/Topshelf.Integrations)

**Comment by stevenfirstrowinc** [comment]
Thanks for your response.  I'm wondering about your factory.  After doing quite a lot of browsing I found that Steve (SimpleInjector) recommends having a decorator that starts a lifetimescope.  I didn't see that in your project, is there a reason?  Here's what I did

````
public class LifetimeScopeDecorator : IJob
    {
        private readonly Func<IJob> _decorateeFactory;
        private readonly Container _container;

        public LifetimeScopeDecorator(Func<IJob> decorateeFactory, Container container)
        {
            _decorateeFactory = decorateeFactory;
            _container = container;
        }

        public void Execute(IJobExecutionContext context)
        {
            using (_container.BeginLifetimeScope())
            {
                var job = _decorateeFactory.Invoke();
                job.Execute(context);
            }
        }
    }
````

Am I missing something? I'm not that fluent with Quartz so I'm wondering if you have a reason for not having this?

I was able to use your project, and it allows me to inject my own factory to be able to use this decorator, but I wanted to make sure I wasn't over complicated.

````
    public class SimpleInjectorJobFactory : IJobFactory
    {
        private readonly Func<Type, IJob> _jobFactory;

        public SimpleInjectorJobFactory(Func<Type, IJob> jobFactory)
        {
            _jobFactory = jobFactory;
        }

        public void ReturnJob(IJob job)
        {
            //throw new NotImplementedException();
        }

        public IJob NewJob(TriggerFiredBundle bundle, IScheduler scheduler)
        {
            return _jobFactory(bundle.JobDetail.JobType);
        }
    }
````
Appreciate your thoughts.

**Comment by tynor88** [comment]
@stevenfirstrowinc I was looking through the prefered way of integrating [Simple Injector](https://github.com/simpleinjector) with [Quartz.NET](https://github.com/quartznet/quartznet), and it seems @dotnetjunkie has modified his post on [stackoverflow](http://stackoverflow.com/questions/14562176/constructor-injection-with-quartz-net-and-simple-injector) lately. When i made the implementation i was using [this revision](http://stackoverflow.com/revisions/14562660/5) however the [answer was updated](http://stackoverflow.com/revisions/14562660/9) the 22nd of February by Steve. 

I have been using the former version of integrating the two frameworks in many projects, and i haven't experienced any errors.

I see no reason why you would have to start a new [lifetime scope](http://simpleinjector.readthedocs.org/en/latest/lifetimes.html#per-lifetime-scope) unless you're playing with hybrid lifestyles as you can see an [example of here](http://stackoverflow.com/questions/21879646/unitofwork-in-wcf-with-quartz-threads)

Perhaps @dotnetjunkie can answer why the answer and prefered way of integrating the two frameworks was changed on stackoverflow?

**Comment by dotnetjunkie** [comment]
Hmmm, yes, I had a hard time figuring out why I did that change. This proves the importants of adding real comments with your revisions :-)

The main reason for that change is to make it easier for the user to register IJob decorators in Simple Injector. The old revision resolves a concrete job type from the container, and this disallows the container from applying any decorators (since decorators can obviously only be applied to the abstraction). Although decorators could be added manually inside the `SimpleInjectorJobFactory`, this becomes more challenging when decorators contain dependencies of their own, when those decorators contain [decoratee factories](https://simpleinjector.readthedocs.org/en/latest/advanced.html#decorators-with-func-t-decoratee-factories), or when decorators need to be applied conditionally.

**Comment by stevenfirstrowinc** [comment]
@dotnetjunkie Thanks for the additional info.  @tynor88 what do you think, will you update your factory to use this approach?

**Comment by tynor88** [comment]
@stevenfirstrowinc Yes, I think it's a good idea. I will have a look at it.

**Comment by tynor88** [comment]
@stevenfirstrowinc I have published a [new version of the Topshelf.SimpleInjector.Quartz](https://www.nuget.org/packages/Topshelf.SimpleInjector.Quartz/) NuGet package which has support for [IJob decorators](https://simpleinjector.readthedocs.org/en/latest/advanced.html#decorators) and [decoratee Func<T> factories](https://simpleinjector.readthedocs.org/en/latest/advanced.html#decorators-with-func-t-decoratee-factories).

Basically there is a new overload method which you have to call when configuring the framework:

```cs
config.UseQuartzSimpleInjectorWithDecorators(_container, Assembly.GetExecutingAssembly());
```

I have made a [sample project](https://github.com/tynor88/Topshelf.SimpleInjector/blob/master/Samples/Topshelf.SimpleInjector.Quartz.Decorators.Sample/Program.cs) where you can see an example of how you can use Topshelf and SimpleInjector with chained IJob (Quartz job) decorators.

Please let me know if this resolves your question.

**Comment by tynor88** [comment]
Oh, and I also updated the Topshelf, Quartz.NET and SimpleInjector packages to the newest versions, and targeted the .NET framework to 4.0 instead of 4.5.

**Comment by stevenfirstrowinc** [comment]
awesome!  thanks for doing this
