### ISSUE TITLE
Needs to skip app path using Environment.GetCommandLineArgs().Skip(1)

### ISSUE THREAD

**Issue by tohagan** [tynor88/Topshelf.SimpleInjector#5]
I ran the unit test suite and was using Reshaper Runner that happened to include the word "Installation" as part of the Runner path (this is probably the default installation directory). Consequently [Line 56 in SimpleInjectorScheduleJobServiceConfiguratorExtensions.cs](https://github.com/tynor88/Topshelf.SimpleInjector/blob/master/Source/Topshelf.SimpleInjector.Quartz/SimpleInjectorScheduleJobServiceConfiguratorExtensions.cs#L56) caused a unit test to fail:

`Environment.GetCommandLineArgs()` needs to be `Environment.GetCommandLineArgs().Skip(1)`

Thanks!

**Comment by tynor88** [comment]
@tohagan This is now fixed. Please see commit: https://github.com/tynor88/Topshelf.SimpleInjector/commit/11f5448227f7a8f258f3b897af1abaf41eb6e6d2 for code details.

**Comment by tohagan** [comment]
Thanks very much!
