### ISSUE TITLE
Unit test throws (and hides) NullException due to SimpleInjectorHostBuilderConfigurator.Container being static

### ISSUE THREAD

**Issue by tohagan** [tynor88/Topshelf.SimpleInjector#6]
Looks a bit weird that the constructor is used to initialise a static value.

**Comment by tynor88** [comment]
Any reason why this was closed again?

**Comment by tohagan** [comment]
Will be back in the office tomorrow so will try to remember to recheck this.

**Comment by tynor88** [comment]
All unit tests now runs in a new AppDomain due to Topshelf being Static. Should fix any issues with running the Tests.

See commit: https://github.com/tynor88/Topshelf.SimpleInjector/commit/f0b272ccf9c5d1b989e78507482d6e84abd60b37
